[ci]
#backfill=365
[pypi]
#backfill = 365
packages = [
    "ibis-framework",
]
[github]
repos = [
    "ibis-project/ibis",
    #"ibis-project/ibis-examples",
]
endpoints = [
    "repo",
    "stargazers",
    "subscribers",
    "commits",
    "releases",
    "forks",
    "issues",
    "contributors",
]
