[app]
database="data/backup.ddb"
#database="md:prod_metrics"

[eda]
database="md:prod_metrics"
#database="data/backup.ddb"

[ingest.pypi]
packages = [
    "ibis-framework",
]
[ingest.github]
repos = [
    "ibis-project/ibis",
]
endpoints = [
    "repo",
    "stargazers",
    "subscribers",
    "commits",
    "releases",
    "forks",
    "issues",
    "contributors",
]
