[app]
#database="app.ddb"
database="md:metrics"
[eda]
database="cache.ddb"
#database="md:metrics"

[prod]
staging="stage.ddb"
prod="prod.ddb"

[ingest.ci]
#backfill=365
[ingest.pypi]
#backfill = 365
packages = [
    "ibis-framework",
]
[ingest.github]
repos = [
    "ibis-project/ibis",
    #"ibis-project/ibis-examples",
]
endpoints = [
    "repo",
    "stargazers",
    "subscribers",
    "commits",
    "releases",
    "forks",
    "issues",
    "contributors",
]
[ingest.goat]
directory = "goat-export"
blob_name = "goatcounter-export-ibis.csv.gz"

[motherduck]
database="metrics"
exclude_tables = ["penguins"]

[azure]
account_name = "notonedrive"
directory = "metrics-backup"
blob_name = "cache.ddb"

