[app]
#database="backup.ddb"
database="md:prod_metrics"
[eda]
#database="md:prod_metrics"
database="backup.ddb"

[prod]
staging="stage.ddb"
prod="prod.ddb"

[ingest.ci]
#backfill=365
[ingest.pypi]
#backfill = 365
packages = [
    "ibis-framework",
    "substrait",
    "ibis-substrait",
]
[ingest.github]
repos = [
    "ibis-project/ibis",
    "ibis-project/ibis-examples",
    "substrait-io/substrait",
    "substrait-io/substrait-python",
    "ibis-project/ibis-substrait",
    "ibis-project/ibis-examples",
]
endpoints = [
    "repo",
    "stargazers",
    "subscribers",
    "commits",
    "releases",
    "forks",
    "issues",
    "contributors",
]
[ingest.goat]
directory = "goat-export"
blob_name = "goatcounter-export-ibis.csv.gz"
