project:
  type: website
  output-dir: _output

# website
website:
  # basics
  title: "Ibis analytics"
  description: "Ibis analytics with Ibis."
  #favicon: logo.png
  search: false

  # options
  reader-mode: false
  twitter-card: true
  back-to-top-navigation: true
  repo-url: https://github.com/ibis-project/ibis-analytics

  # footer
  page-footer:
    border: false
    center: "Ibis analytics"
    right:
      - icon: github
        href: https://github.com/ibis-project/ibis-analytics

# theme
format:
  html:
    theme: darkly
    toc: true
